export const LOADING = 'LOADING'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const REGISTER_USER = 'REGISTER_USER'
